const h = ''
// const h = '/ds'
export const TeacherRoomList = `${h}/room/teacherRoomList`
export const TeacherRoomFirst = `${h}/room/teacherRoomFirst`
export const GetRoomName = `${h}/room/getNameById`
export const GetTeamName = `${h}/team/getNameById`
export const QueryByName = `${h}/student/queryByNameRoomId`
export const TotalByName = `${h}/student/totalByNameRoomId`
export const GetById = `${h}/student/getById`
export const GetParent = `${h}/student/getParentById`
