INSERT INTO `Enterprise` (userId,name, account, mobile) VALUES ('chnwts', '王天硕', 'wts', '18653145531');
INSERT INTO `Teacher` (enterprise_id,name,login,mobile,pass,system) VALUES ('1','王天硕', 'wts', '18653145531', 'wts', '1');
INSERT INTO `Course` (id,name,state) VALUES ('1', '班主任', '1');
INSERT INTO `Course` (id,name,state) VALUES ('2', '语文', '1');
INSERT INTO `Course` (id,name,state) VALUES ('3', '数学', '1');
INSERT INTO `Course` (id,name,state) VALUES ('4', '英语', '1');
INSERT INTO `Identity` (id,name) VALUES ('1', '爸爸');
INSERT INTO `Identity` (id,name) VALUES ('2', '妈妈');
INSERT INTO `Identity` (id,name) VALUES ('3', '爷爷');
INSERT INTO `Identity` (id,name) VALUES ('4', '奶奶');
INSERT INTO `Identity` (id,name) VALUES ('5', '姥姥');
INSERT INTO `Identity` (id,name) VALUES ('6', '姥爷');