INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('1', '2016第一学期', NULL, NULL, '0', '0');
INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('2', '2016第二学期', NULL, NULL, '0', '0');
INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('3', '2017第一学期', NULL, NULL, '1', '0');
INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('4', '2017第二学期', NULL, NULL, '0', '0');
INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('5', '2018第一学期', NULL, NULL, '0', '0');
INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('6', '2018第二学期', NULL, NULL, '0', '0');
INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('7', '2019第一学期', NULL, NULL, '0', '0');
INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('8', '2019第二学期', NULL, NULL, '0', '0');
INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('9', '2020第一学期', NULL, NULL, '0', '0');
INSERT INTO `school_service`.`semester` (`id`, `name`, `time_start`, `time_end`, `state`, `del`) VALUES ('10', '2020第二学期', NULL, NULL, '0', '0');

INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('1', '2011级1班', '2011', '1', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('2', '2011级2班', '2011', '2', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('3', '2011级3班', '2011', '3', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('4', '2012级1班', '2012', '1', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('5', '2012级2班', '2012', '2', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('6', '2012级3班', '2012', '3', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('7', '2013级1班', '2013', '1', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('8', '2013级2班', '2013', '2', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('9', '2013级3班', '2013', '3', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('10', '2014级1班', '2014', '1', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('11', '2014级2班', '2014', '2', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('12', '2014级3班', '2014', '3', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('13', '2015级1班', '2015', '1', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('14', '2015级2班', '2015', '2', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('15', '2015级3班', '2015', '3', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('16', '2016级1班', '2016', '1', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('17', '2016级2班', '2016', '2', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('18', '2016级3班', '2016', '3', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('19', '2017级1班', '2017', '1', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('20', '2017级2班', '2017', '2', '1', '0');
INSERT INTO `school_service`.`room` (`id`, `name`, `year`, `order`, `state`, `del`) VALUES ('21', '2017级3班', '2017', '3', '1', '0');

INSERT INTO `school_service`.`identity` (`id`, `name`) VALUES ('1', '爸爸');
INSERT INTO `school_service`.`identity` (`id`, `name`) VALUES ('2', '妈妈');
INSERT INTO `school_service`.`identity` (`id`, `name`) VALUES ('3', '爷爷');
INSERT INTO `school_service`.`identity` (`id`, `name`) VALUES ('4', '奶奶');
INSERT INTO `school_service`.`identity` (`id`, `name`) VALUES ('5', '外公');
INSERT INTO `school_service`.`identity` (`id`, `name`) VALUES ('6', '外婆');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('1', '班主任', 'a', '0', '1', '0', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('2', '语文', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('3', '数学', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('4', '英语', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('5', '音乐', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('6', '体育', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('7', '美术', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('8', '科学', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('9', '计算机', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('10', '品生', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('11', '品社', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('12', '传统文化', 'a', '0', '1', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('13', '绘本阅读之旅', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('14', '缤纷合唱团', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('15', '国学社', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('16', '国际跳棋', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('17', '创意三角插', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('18', '诵读经典', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('19', '花样衍纸', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('20', '国际跳棋', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('21', 'IT精英', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('22', '传统游戏', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('23', '阳光少年礼仪形象训练营', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('24', '玩转魔方', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('25', '趣味田径', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('26', '篮球', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('27', '美八度', 'a', '50', '2', '1', '0');
INSERT INTO `school_service`.`course` (`id`, `name`, `detail`, `amount`, `type`, `state`, `del`) VALUES ('28', '国际数棋', 'a', '50', '2', '1', '0');
