package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLeave<M extends BaseLeave<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setFlow(java.lang.Integer flow) {
		set("flow", flow);
	}

	public java.lang.Integer getFlow() {
		return get("flow");
	}

	public void setParentContent(java.lang.String parentContent) {
		set("parentContent", parentContent);
	}

	public java.lang.String getParentContent() {
		return get("parentContent");
	}

	public void setTeacherContent(java.lang.String teacherContent) {
		set("teacherContent", teacherContent);
	}

	public java.lang.String getTeacherContent() {
		return get("teacherContent");
	}

	public void setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
	}

	public java.lang.Integer getStudentId() {
		return get("student_id");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Integer getParentId() {
		return get("parent_id");
	}

	public void setTeacherId(java.lang.Integer teacherId) {
		set("teacher_id", teacherId);
	}

	public java.lang.Integer getTeacherId() {
		return get("teacher_id");
	}

	public void setSchoolId(java.lang.Integer schoolId) {
		set("school_id", schoolId);
	}

	public java.lang.Integer getSchoolId() {
		return get("school_id");
	}

	public void setTimeApply(java.util.Date timeApply) {
		set("time_apply", timeApply);
	}

	public java.util.Date getTimeApply() {
		return get("time_apply");
	}

	public void setTimeRatify(java.util.Date timeRatify) {
		set("time_ratify", timeRatify);
	}

	public java.util.Date getTimeRatify() {
		return get("time_ratify");
	}

	public void setTimeStart(java.util.Date timeStart) {
		set("time_start", timeStart);
	}

	public java.util.Date getTimeStart() {
		return get("time_start");
	}

	public void setTimeEnd(java.util.Date timeEnd) {
		set("time_end", timeEnd);
	}

	public java.util.Date getTimeEnd() {
		return get("time_end");
	}

}
