package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSchedule<M extends BaseSchedule<M>> extends Model<M> implements IBean {

	public void setOrderDay(java.lang.Integer orderDay) {
		set("order_day", orderDay);
	}

	public java.lang.Integer getOrderDay() {
		return get("order_day");
	}

	public void setOrderCourse(java.lang.Integer orderCourse) {
		set("order_course", orderCourse);
	}

	public java.lang.Integer getOrderCourse() {
		return get("order_course");
	}

	public void setSemesterId(java.lang.Integer semesterId) {
		set("semester_id", semesterId);
	}

	public java.lang.Integer getSemesterId() {
		return get("semester_id");
	}

	public void setTimeStart(java.util.Date timeStart) {
		set("time_start", timeStart);
	}

	public java.util.Date getTimeStart() {
		return get("time_start");
	}

	public void setTimeEnd(java.util.Date timeEnd) {
		set("time_end", timeEnd);
	}

	public java.util.Date getTimeEnd() {
		return get("time_end");
	}

}
