package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApplication<M extends BaseApplication<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAgentId(java.lang.Integer agentId) {
		set("agentId", agentId);
	}

	public java.lang.Integer getAgentId() {
		return get("agentId");
	}

	public void setSchoolId(java.lang.Integer schoolId) {
		set("school_id", schoolId);
	}

	public java.lang.Integer getSchoolId() {
		return get("school_id");
	}

	public void setQyId(java.lang.Integer qyId) {
		set("qy_id", qyId);
	}

	public java.lang.Integer getQyId() {
		return get("qy_id");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setRedirectDomain(java.lang.String redirectDomain) {
		set("redirect_domain", redirectDomain);
	}

	public java.lang.String getRedirectDomain() {
		return get("redirect_domain");
	}

	public void setReportLocationFlag(java.lang.Integer reportLocationFlag) {
		set("report_location_flag", reportLocationFlag);
	}

	public java.lang.Integer getReportLocationFlag() {
		return get("report_location_flag");
	}

	public void setChatExtensionUrl(java.lang.String chatExtensionUrl) {
		set("chat_extension_url", chatExtensionUrl);
	}

	public java.lang.String getChatExtensionUrl() {
		return get("chat_extension_url");
	}

	public void setIsreportuser(java.lang.Integer isreportuser) {
		set("isreportuser", isreportuser);
	}

	public java.lang.Integer getIsreportuser() {
		return get("isreportuser");
	}

	public void setIsreportenter(java.lang.Integer isreportenter) {
		set("isreportenter", isreportenter);
	}

	public java.lang.Integer getIsreportenter() {
		return get("isreportenter");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setHomeUrl(java.lang.String homeUrl) {
		set("home_url", homeUrl);
	}

	public java.lang.String getHomeUrl() {
		return get("home_url");
	}

}
