package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSchoolQy<M extends BaseSchoolQy<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setCorpId(java.lang.String corpId) {
		set("corpId", corpId);
	}

	public java.lang.String getCorpId() {
		return get("corpId");
	}

	public void setCorpSecret(java.lang.String corpSecret) {
		set("corpSecret", corpSecret);
	}

	public java.lang.String getCorpSecret() {
		return get("corpSecret");
	}

	public void setSchoolId(java.lang.Integer schoolId) {
		set("school_id", schoolId);
	}

	public java.lang.Integer getSchoolId() {
		return get("school_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
