package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCoursechoose<M extends BaseCoursechoose<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCourseId(java.lang.Integer courseId) {
		set("course_id", courseId);
	}

	public java.lang.Integer getCourseId() {
		return get("course_id");
	}

	public void setSemesterId(java.lang.Integer semesterId) {
		set("semester_id", semesterId);
	}

	public java.lang.Integer getSemesterId() {
		return get("semester_id");
	}

	public void setTimeStart(java.util.Date timeStart) {
		set("time_start", timeStart);
	}

	public java.util.Date getTimeStart() {
		return get("time_start");
	}

	public void setTimeEnd(java.util.Date timeEnd) {
		set("time_end", timeEnd);
	}

	public java.util.Date getTimeEnd() {
		return get("time_end");
	}

	public void setTotal(java.lang.Integer total) {
		set("total", total);
	}

	public java.lang.Integer getTotal() {
		return get("total");
	}

	public void setLess(java.lang.Integer less) {
		set("less", less);
	}

	public java.lang.Integer getLess() {
		return get("less");
	}

}
