package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoom<M extends BaseRoom<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRoomYear(java.lang.String roomYear) {
		set("roomYear", roomYear);
	}

	public java.lang.String getRoomYear() {
		return get("roomYear");
	}

	public void setRoomOrder(java.lang.String roomOrder) {
		set("roomOrder", roomOrder);
	}

	public java.lang.String getRoomOrder() {
		return get("roomOrder");
	}

	public void setRoomSlogan(java.lang.String roomSlogan) {
		set("roomSlogan", roomSlogan);
	}

	public java.lang.String getRoomSlogan() {
		return get("roomSlogan");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

}
