package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEnterprise<M extends BaseEnterprise<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setPass(java.lang.String pass) {
		set("pass", pass);
	}

	public java.lang.String getPass() {
		return get("pass");
	}

	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}

	public java.lang.String getOpenId() {
		return get("openId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setWork(java.lang.String work) {
		set("work", work);
	}

	public java.lang.String getWork() {
		return get("work");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setWeixinId(java.lang.String weixinId) {
		set("weixinId", weixinId);
	}

	public java.lang.String getWeixinId() {
		return get("weixinId");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setPicUrl(java.lang.String picUrl) {
		set("picUrl", picUrl);
	}

	public java.lang.String getPicUrl() {
		return get("picUrl");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setIsTeacher(java.lang.Integer isTeacher) {
		set("isTeacher", isTeacher);
	}

	public java.lang.Integer getIsTeacher() {
		return get("isTeacher");
	}

	public void setIsParent(java.lang.Integer isParent) {
		set("isParent", isParent);
	}

	public java.lang.Integer getIsParent() {
		return get("isParent");
	}

	public void setIsManager(java.lang.Integer isManager) {
		set("isManager", isManager);
	}

	public java.lang.Integer getIsManager() {
		return get("isManager");
	}

}
