package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSemester<M extends BaseSemester<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTimeStart(java.util.Date timeStart) {
		set("time_start", timeStart);
	}

	public java.util.Date getTimeStart() {
		return get("time_start");
	}

	public void setTimeEnd(java.util.Date timeEnd) {
		set("time_end", timeEnd);
	}

	public java.util.Date getTimeEnd() {
		return get("time_end");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

}
