package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCourseplan<M extends BaseCourseplan<M>> extends Model<M> implements IBean {

	public void setCourseId(java.lang.Integer courseId) {
		set("course_id", courseId);
	}

	public java.lang.Integer getCourseId() {
		return get("course_id");
	}

	public void setTeacherId(java.lang.Integer teacherId) {
		set("teacher_id", teacherId);
	}

	public java.lang.Integer getTeacherId() {
		return get("teacher_id");
	}

	public void setRoomId(java.lang.Integer roomId) {
		set("room_id", roomId);
	}

	public java.lang.Integer getRoomId() {
		return get("room_id");
	}

	public void setSequence(java.lang.Integer sequence) {
		set("sequence", sequence);
	}

	public java.lang.Integer getSequence() {
		return get("sequence");
	}

}
