const h = ''
// const h = '/ds'
export const TeacherGetName = `${h}/teacher/getName`
export const TeacherCheckNameForNew = `${h}/teacher/checkNameForNew`
export const TeacherCheckPhoneForNew = `${h}/teacher/checkPhoneForNew`
export const TeacherCheckWeixinForNew = `${h}/teacher/checkWeixinForNew`
export const TeacherCheckEmailForNew = `${h}/teacher/checkEmailForNew`
export const TeacherCheckNameForEdit = `${h}/teacher/checkNameForEdit`
export const TeacherCheckPhoneForEdit = `${h}/teacher/checkPhoneForEdit`
export const TeacherCheckWeixinForEdit = `${h}/teacher/checkWeixinForEdit`
export const TeacherCheckEmailForEdit = `${h}/teacher/checkEmailForEdit`
export const TeacherSave = `${h}/teacher/save`
export const TeacherEdit = `${h}/teacher/edit`
export const TeacherQueryByName = `${h}/teacher/queryByName`
export const TeacherGetById = `${h}/teacher/getById`
export const TeacherDeleteById = `${h}/teacher/deleteById`
