const h = ''
// const h = '/ds'
export const TeacherGetName = `${h}/teacher/getName`
export const TeacherCheckName = `${h}/teacher/checkName`
export const TeacherCheckPhone = `${h}/teacher/checkPhone`
export const TeacherCheckWeixin = `${h}/teacher/checkWeixin`
export const TeacherCheckEmail = `${h}/teacher/checkEmail`
export const TeacherSave = `${h}/teacher/save`
export const TeacherQuery = `${h}/teacher/query`
