const h = ''
// const h = '/ds'
export const CheckNameForNew = `${h}/room/checkNameForNew`
export const CheckLoginForNew = `${h}/room/checkLoginForNew`
export const CheckPhoneForNew = `${h}/room/checkPhoneForNew`
export const CheckWeixinForNew = `${h}/room/checkWeixinForNew`
export const CheckEmailForNew = `${h}/room/checkEmailForNew`
export const CheckNameForEdit = `${h}/room/checkNameForEdit`
export const CheckPhoneForEdit = `${h}/room/checkPhoneForEdit`
export const CheckWeixinForEdit = `${h}/room/checkWeixinForEdit`
export const CheckEmailForEdit = `${h}/room/checkEmailForEdit`
export const Save = `${h}/room/save`
export const Edit = `${h}/room/edit`
export const QueryByName = `${h}/room/queryByName`
export const TotalByName = `${h}/room/totalByName`
export const GetById = `${h}/room/getById`
export const DeleteById = `${h}/room/deleteById`
