const h = ''
// const h = '/ds'
export const GetRoomName = `${h}/room/getNameById`
export const GetTeamName = `${h}/team/getNameById`
export const GetParent = `${h}/student/getParentById`
export const Delete = `${h}/parent/deleteForParent`
export const Add = `${h}/parent/addForParent`
export const IdentityList = `${h}/identity/identityList`
export const Edit = `${h}/student/editForParent`
export const Query = `${h}/student/queryForParent`
export const Total = `${h}/student/totalForParent`
export const GetById = `${h}/student/getById`
