const h = ''
// const h = '/ds'
export const ParentRoomList = `${h}/room/parentRoomList`
export const ParentRoomFirst = `${h}/room/parentRoomFirst`
export const GetRoomName = `${h}/room/getNameById`
export const GetCourseName = `${h}/course/getNameById`
export const GetTeacherName = `${h}/enterprise/getNameById`
export const Read = `${h}/roomworkread/readRoomworkById`
export const GetRoomworkreadState = `${h}/roomworkread/readRoomworkStateById`
export const Query = `${h}/roomwork/queryForParent`
export const Total = `${h}/roomwork/totalForParent`
export const GetById = `${h}/roomwork/getById`
