const h = ''
// const h = '/ds'
export const CheckNameForNew = `${h}/teacher/checkNameForNew`
export const CheckUserIdForNew = `${h}/teacher/checkUserIdForNew`
export const CheckMobileForNew = `${h}/teacher/checkMobileForNew`
export const CheckNameForEdit = `${h}/teacher/checkNameForEdit`
export const GetUserId = `${h}/teacher/getUserId`
export const CheckMobileForEdit = `${h}/teacher/checkMobileForEdit`
export const Save = `${h}/teacher/save`
export const Edit = `${h}/teacher/edit`
export const Query = `${h}/teacher/query`
export const TotalByName = `${h}/teacher/totalByName`
export const GetById = `${h}/teacher/getById`
export const DeleteById = `${h}/teacher/deleteById`
export const ResaveById = `${h}/teacher/resaveById`
