import * as Mobile from '../../Mobile.js'
const base = 'parent'
const base2 = 'Teacher'
export const checkName = `${Mobile.Prefix}/${base2}/checkName`
export const checkMobileForAdd = `${Mobile.Prefix}/${base2}/checkMobileForAdd`
export const checkMobileForEdit = `${Mobile.Prefix}/${base}/checkMobileForEdit`
export const checkEmailForAdd = `${Mobile.Prefix}/${base2}/checkEmailForAdd`
export const checkEmailForEdit = `${Mobile.Prefix}/${base}/checkEmailForEdit`
export const checkQQForAdd = `${Mobile.Prefix}/${base2}/checkQQForAdd`
export const checkQQForEdit = `${Mobile.Prefix}/${base}/checkQQForEdit`
export const checkWeixinIdForAdd = `${Mobile.Prefix}/${base2}/checkWeixinIdForAdd`
export const checkWeixinIdForEdit = `${Mobile.Prefix}/${base}/checkWeixinIdForEdit`
export const save = `${Mobile.Prefix}/${base}/save`
export const edit = `${Mobile.Prefix}/${base}/edit`
export const active = `${Mobile.Prefix}/${base}/active`
export const inactive = `${Mobile.Prefix}/${base}/inactive`
export const get = `${Mobile.Prefix}/${base}/get`
export const query = `${Mobile.Prefix}/${base}/query`
export const total = `${Mobile.Prefix}/${base}/total`
