const h = ''
// const h = '/ds'
export const TeacherTeamList = `${h}/team/teacherTeamList`
export const TeacherTeamFirst = `${h}/team/teacherTeamFirst`
export const GetTeamName = `${h}/team/getNameById`
export const GetTeacherName = `${h}/enterprise/getNameById`
export const StudentList = `${h}/student/studentListByTeam`
export const StudentCode = `${h}/student/studentCodeByTeam`
export const Query = `${h}/teamwork/queryByTeamId`
export const Total = `${h}/teamwork/totalByTeamId`
export const GetById = `${h}/teamwork/getById`
export const Save = `${h}/teamwork/save`
export const Send = `${h}/teamworkread/send`
export const Inactive = `${h}/teamwork/inactiveById`
export const GetReadTeamwork = `${h}/teamworkread/getReadTeamwork`
export const GetUnreadTeamwork = `${h}/teamworkread/getUnreadTeamwork`
