const h = ''
// const h = '/yuming'
/* eslint-disable camelcase */
export const Login = `${h}/login`
export const Semester_CheckName_Add = `${h}/semester/checkNameForAdd`
export const Semester_CheckName_Edit = `${h}/semester/checkNameForEdit`
export const Semester_Save = `${h}/semester/save`
export const Semester_Edit = `${h}/semester/edit`
export const Semester_Active = `${h}/semester/active`
export const Semester_Get = `${h}/semester/get`
export const Semester_Query = `${h}/semester/query`
export const Semester_Total = `${h}/semester/total`
export const Course_CheckName_Add = `${h}/course/checkNameForAdd`
export const Course_CheckName_Edit = `${h}/course/checkNameForEdit`
export const Course_Save = `${h}/course/save`
export const Course_Edit = `${h}/course/edit`
export const Course_Active = `${h}/course/active`
export const Course_Inactive = `${h}/course/inactive`
export const Course_Get = `${h}/course/get`
export const Course_Query = `${h}/course/query`
export const Course_Total = `${h}/course/total`
