const h = ''
// const h = '/ds'
export const TeacherRoomList = `${h}/room/teacherRoomList`
export const TeacherRoomFirst = `${h}/room/teacherRoomFirst`
export const RoomCourseList = `${h}/room/roomCourseList`
export const RoomCourseFirst = `${h}/room/roomCourseFirst`
export const GetRoomName = `${h}/room/getNameById`
export const GetCourseName = `${h}/course/getNameById`
export const GetTeacherName = `${h}/enterprise/getNameById`
export const StudentList = `${h}/student/studentListByRoom`
export const Query = `${h}/roomwork/queryByRoomId`
export const Total = `${h}/roomwork/totalByRoomId`
export const GetById = `${h}/roomwork/getById`
export const Save = `${h}/roomwork/save`
export const Send = `${h}/roomworkread/send`
export const Inactive = `${h}/roomwork/inactiveById`
export const GetReadRoomwork = `${h}/roomworkread/getReadRoomwork`
export const GetUnreadRoomwork = `${h}/roomworkread/getUnreadRoomwork`
