package com.wts.entity.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("application", "id", Application.class);
		arp.addMapping("course", "id", Course.class);
		arp.addMapping("identity", "id", Identity.class);
		arp.addMapping("menu", "id", Menu.class);
		arp.addMapping("parent", "id", Parent.class);
		arp.addMapping("room", "id", Room.class);
		arp.addMapping("school", "id", School.class);
		arp.addMapping("school_dy", "id", SchoolDy.class);
		arp.addMapping("school_fw", "id", SchoolFw.class);
		arp.addMapping("school_qy", "id", SchoolQy.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("tag", "id", Tag.class);
		arp.addMapping("teacher", "id", Teacher.class);
		arp.addMapping("user_dy", "id", UserDy.class);
		arp.addMapping("user_fw", "id", UserFw.class);
		arp.addMapping("user_qy", "id", UserQy.class);
	}
}

