package com.wts.entity.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("course", "id", Course.class);
		arp.addMapping("enterprise", "id", Enterprise.class);
		arp.addMapping("exam", "id", Exam.class);
		arp.addMapping("grade", "id", Grade.class);
		arp.addMapping("identity", "id", Identity.class);
		arp.addMapping("leave", "id", Leave.class);
		arp.addMapping("notice", "id", Notice.class);
		arp.addMapping("praise", "id", Praise.class);
		arp.addMapping("praisedetail", "id", Praisedetail.class);
		arp.addMapping("relation", "id", Relation.class);
		arp.addMapping("room", "id", Room.class);
		arp.addMapping("roomplan", "id", Roomplan.class);
		arp.addMapping("roomwork", "id", Roomwork.class);
		arp.addMapping("roomworkread", "id", Roomworkread.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("team", "id", Team.class);
		arp.addMapping("teamplan", "id", Teamplan.class);
		arp.addMapping("teamwork", "id", Teamwork.class);
		arp.addMapping("teamworkread", "id", Teamworkread.class);
	}
}

