package com.wts.entity.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("course", "id", Course.class);
		arp.addMapping("courseplan", "id", Courseplan.class);
		arp.addMapping("enterprise", "id", Enterprise.class);
		arp.addMapping("exam", "id", Exam.class);
		arp.addMapping("grade", "id", Grade.class);
		arp.addMapping("homework", "id", Homework.class);
		arp.addMapping("homeworkread", "id", Homeworkread.class);
		arp.addMapping("identity", "id", Identity.class);
		arp.addMapping("leave", "id", Leave.class);
		arp.addMapping("notice", "id", Notice.class);
		arp.addMapping("parent", "id", Parent.class);
		arp.addMapping("praise", "id", Praise.class);
		arp.addMapping("relation", "id", Relation.class);
		arp.addMapping("room", "id", Room.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("teacher", "id", Teacher.class);
	}
}

