package com.wts.entity.model;

import com.wts.entity.base.BaseApplication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Application extends BaseApplication<Application> {
	public static final Application dao = new Application();
}
