package com.wts.entity.model;

import com.wts.entity.base.BaseAssessment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Assessment extends BaseAssessment<Assessment> {
	public static final Assessment dao = new Assessment().dao();
}
