package com.wts.entity.model;

import com.wts.entity.base.BaseAssessmentdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Assessmentdetail extends BaseAssessmentdetail<Assessmentdetail> {
	public static final Assessmentdetail dao = new Assessmentdetail().dao();
}
