package com.wts.entity.model;

import com.wts.entity.base.BaseCoursestudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coursestudent extends BaseCoursestudent<Coursestudent> {
	public static final Coursestudent dao = new Coursestudent().dao();
}
