package com.wts.entity.model;

import com.wts.entity.base.BaseCoursemessageread;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coursemessageread extends BaseCoursemessageread<Coursemessageread> {
	public static final Coursemessageread dao = new Coursemessageread().dao();
}
