package com.wts.entity.model;

import com.wts.entity.base.BaseCoursechoosedetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coursechoosedetail extends BaseCoursechoosedetail<Coursechoosedetail> {
	public static final Coursechoosedetail dao = new Coursechoosedetail().dao();
}
