package com.wts.entity.model;

import com.wts.entity.base.BaseCourseroom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Courseroom extends BaseCourseroom<Courseroom> {
	public static final Courseroom dao = new Courseroom().dao();
}
