package com.wts.entity.model;

import com.wts.entity.base.BaseCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Course extends BaseCourse<Course> {
	public static final Course dao = new Course().dao();
}
