package com.wts.entity.model;

import com.wts.entity.base.BaseCoursechoose;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coursechoose extends BaseCoursechoose<Coursechoose> {
	public static final Coursechoose dao = new Coursechoose().dao();
}
