package com.wts.entity.model;

import com.wts.entity.base.BaseCourseroomteacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Courseroomteacher extends BaseCourseroomteacher<Courseroomteacher> {
	public static final Courseroomteacher dao = new Courseroomteacher().dao();
}
