package com.wts.entity.model;

import com.wts.entity.base.BaseCourseroomteachersemester;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Courseroomteachersemester extends BaseCourseroomteachersemester<Courseroomteachersemester> {
	public static final Courseroomteachersemester dao = new Courseroomteachersemester().dao();
}
