package com.wts.entity.model;

import com.wts.entity.base.BaseCourseplan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Courseplan extends BaseCourseplan<Courseplan> {
	public static final Courseplan dao = new Courseplan();
}
