package com.wts.entity.model;

import com.wts.entity.base.BaseCoursemessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coursemessage extends BaseCoursemessage<Coursemessage> {
	public static final Coursemessage dao = new Coursemessage().dao();
}
