package com.wts.entity.model;

import com.wts.entity.base.BaseEnterprise;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Enterprise extends BaseEnterprise<Enterprise> {
	public static final Enterprise dao = new Enterprise();
}
