package com.wts.entity.model;

import com.jfinal.plugin.activerecord.Page;
import com.wts.entity.base.BaseEnterprise;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Enterprise extends BaseEnterprise<Enterprise> {
	public static final Enterprise dao = new Enterprise();
	public Page<Enterprise> teacherQuery(int pageNumber, int pageSize, String queryString) {
		return paginate(pageNumber, pageSize, "SELECT *",
						"FROM enterprise WHERE (name LIKE '%"+queryString+"%' or mobile LIKE '%"+queryString+"%' or userId LIKE '%"+queryString+"%') ORDER BY id DESC");
	}
}
