package com.wts.entity.model;

import com.wts.entity.base.BaseExam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Exam extends BaseExam<Exam> {
	public static final Exam dao = new Exam().dao();
}
