package com.wts.entity.model;

import com.wts.entity.base.BaseGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Grade extends BaseGrade<Grade> {
	public static final Grade dao = new Grade();
}
