package com.wts.entity.model;

import com.wts.entity.base.BaseHomeworkread;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Homeworkread extends BaseHomeworkread<Homeworkread> {
	public static final Homeworkread dao = new Homeworkread().dao();
}
