package com.wts.entity.model;

import com.wts.entity.base.BaseHomeworkdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Homeworkdetail extends BaseHomeworkdetail<Homeworkdetail> {
	public static final Homeworkdetail dao = new Homeworkdetail().dao();
}
