package com.wts.entity.model;

import com.wts.entity.base.BaseHomework;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Homework extends BaseHomework<Homework> {
	public static final Homework dao = new Homework().dao();
}
