package com.wts.entity.model;

import com.wts.entity.base.BaseIdentity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Identity extends BaseIdentity<Identity> {
	public static final Identity dao = new Identity().dao();
}
