package com.wts.entity.model;

import com.wts.entity.base.BaseLeave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Leave extends BaseLeave<Leave> {
	public static final Leave dao = new Leave();
}
