package com.wts.entity.model;

import com.wts.entity.base.BaseParent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Parent extends BaseParent<Parent> {
	public static final Parent dao = new Parent().dao();
}
