package com.wts.entity.model;

import com.wts.entity.base.BaseParentmessagesend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Parentmessagesend extends BaseParentmessagesend<Parentmessagesend> {
	public static final Parentmessagesend dao = new Parentmessagesend().dao();
}
