package com.wts.entity.model;

import com.wts.entity.base.BaseParenttag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Parenttag extends BaseParenttag<Parenttag> {
	public static final Parenttag dao = new Parenttag();
}
