package com.wts.entity.model;

import com.wts.entity.base.BaseParentmessageread;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Parentmessageread extends BaseParentmessageread<Parentmessageread> {
	public static final Parentmessageread dao = new Parentmessageread().dao();
}
