package com.wts.entity.model;

import com.wts.entity.base.BasePraise;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Praise extends BasePraise<Praise> {
	public static final Praise dao = new Praise();
}
