package com.wts.entity.model;

import com.wts.entity.base.BaseRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Relation extends BaseRelation<Relation> {
	public static final Relation dao = new Relation().dao();
}
