package com.wts.entity.model;

import com.wts.entity.base.BaseRoomstudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roomstudent extends BaseRoomstudent<Roomstudent> {
	public static final Roomstudent dao = new Roomstudent().dao();
}
