package com.wts.entity.model;

import com.wts.entity.base.BaseRoomworkread;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roomworkread extends BaseRoomworkread<Roomworkread> {
	public static final Roomworkread dao = new Roomworkread().dao();
}
