package com.wts.entity.model;

import com.wts.entity.base.BaseRoomwork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roomwork extends BaseRoomwork<Roomwork> {
	public static final Roomwork dao = new Roomwork().dao();
}
