package com.wts.entity.model;

import com.wts.entity.base.BaseRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Room extends BaseRoom<Room> {
	public static final Room dao = new Room().dao();
}
