package com.wts.entity.model;

import com.wts.entity.base.BaseRoomplan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roomplan extends BaseRoomplan<Roomplan> {
	public static final Roomplan dao = new Roomplan().dao();
}
