package com.wts.entity.model;

import com.wts.entity.base.BaseSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Schedule extends BaseSchedule<Schedule> {
	public static final Schedule dao = new Schedule().dao();
}
