package com.wts.entity.model;

import com.wts.entity.base.BaseSchoolQy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchoolQy extends BaseSchoolQy<SchoolQy> {
	public static final SchoolQy dao = new SchoolQy();
}
