package com.wts.entity.model;

import com.wts.entity.base.BaseSchoolDy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchoolDy extends BaseSchoolDy<SchoolDy> {
	public static final SchoolDy dao = new SchoolDy();
}
