package com.wts.entity.model;

import com.wts.entity.base.BaseSchoolFw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchoolFw extends BaseSchoolFw<SchoolFw> {
	public static final SchoolFw dao = new SchoolFw();
}
