package com.wts.entity.model;

import com.wts.entity.base.BaseSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class School extends BaseSchool<School> {
	public static final School dao = new School();
}
