package com.wts.entity.model;

import com.wts.entity.base.BaseSemester;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Semester extends BaseSemester<Semester> {
	public static final Semester dao = new Semester().dao();
}
