package com.wts.entity.model;

import com.wts.entity.base.BaseStudenttag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Studenttag extends BaseStudenttag<Studenttag> {
	public static final Studenttag dao = new Studenttag();
}
