package com.wts.entity.model;

import com.wts.entity.base.BaseStudentparentidentity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Studentparentidentity extends BaseStudentparentidentity<Studentparentidentity> {
	public static final Studentparentidentity dao = new Studentparentidentity().dao();
}
