package com.wts.entity.model;

import com.wts.entity.base.BaseStudentcoursesemester;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Studentcoursesemester extends BaseStudentcoursesemester<Studentcoursesemester> {
	public static final Studentcoursesemester dao = new Studentcoursesemester().dao();
}
