package com.wts.entity.model;

import com.wts.entity.base.BaseStudentcourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Studentcourse extends BaseStudentcourse<Studentcourse> {
	public static final Studentcourse dao = new Studentcourse().dao();
}
