package com.wts.entity.model;

import com.jfinal.plugin.activerecord.Page;
import com.wts.entity.base.BaseTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tag extends BaseTag<Tag> {
	public static final Tag dao = new Tag();
	public Page<Tag> queryByName(int pageNumber, int pageSize, String name) {
		return paginate(pageNumber, pageSize, "SELECT *",
						"FROM tag WHERE name LIKE '%"+name+"%' ORDER BY id DESC");
	}



}
