package com.wts.entity.model;

import com.wts.entity.base.BaseTeacherpermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacherpermission extends BaseTeacherpermission<Teacherpermission> {
	public static final Teacherpermission dao = new Teacherpermission().dao();
}
