package com.wts.entity.model;

import com.wts.entity.base.BaseTeachermessagesend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teachermessagesend extends BaseTeachermessagesend<Teachermessagesend> {
	public static final Teachermessagesend dao = new Teachermessagesend().dao();
}
