package com.wts.entity.model;

import com.wts.entity.base.BaseTeachertag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teachertag extends BaseTeachertag<Teachertag> {
	public static final Teachertag dao = new Teachertag();
}
