package com.wts.entity.model;

import com.wts.entity.base.BaseTeachermessageread;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teachermessageread extends BaseTeachermessageread<Teachermessageread> {
	public static final Teachermessageread dao = new Teachermessageread().dao();
}
