package com.wts.entity.model;

import com.wts.entity.base.BaseTeachermessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teachermessage extends BaseTeachermessage<Teachermessage> {
	public static final Teachermessage dao = new Teachermessage().dao();
}
