package com.wts.entity.model;

import com.wts.entity.base.BaseTeamworkread;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teamworkread extends BaseTeamworkread<Teamworkread> {
	public static final Teamworkread dao = new Teamworkread().dao();
}
