package com.wts.entity.model;

import com.wts.entity.base.BaseTeamplan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teamplan extends BaseTeamplan<Teamplan> {
	public static final Teamplan dao = new Teamplan().dao();
}
