package com.wts.entity.model;

import com.wts.entity.base.BaseTeamwork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teamwork extends BaseTeamwork<Teamwork> {
	public static final Teamwork dao = new Teamwork().dao();
}
