package com.wts.entity.model;

import com.wts.entity.base.BaseUserFw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFw extends BaseUserFw<UserFw> {
	public static final UserFw dao = new UserFw();
}
