package com.wts.entity.model;

import com.wts.entity.base.BaseUserQy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserQy extends BaseUserQy<UserQy> {
	public static final UserQy dao = new UserQy();
}
