package com.wts.entity.model;

import com.wts.entity.base.BaseUserDy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserDy extends BaseUserDy<UserDy> {
	public static final UserDy dao = new UserDy();
}
