const h = ''
// const h = '/ds'
export const ParentTeamList = `${h}/team/parentTeamList`
export const ParentTeamFirst = `${h}/team/parentTeamFirst`
export const GetTeamName = `${h}/team/getNameById`
export const GetTeacherName = `${h}/enterprise/getNameById`
export const Read = `${h}/teamworkread/readTeamworkById`
export const GetTeamworkreadState = `${h}/teamworkread/readTeamworkStateById`
export const Query = `${h}/teamwork/queryForParent`
export const Total = `${h}/teamwork/totalForParent`
export const GetById = `${h}/teamwork/getById`
