const h = ''
// const h = '/ds'
export const CheckName = `${h}/enterprise/checkName`
export const TeamList = `${h}/team/teamList`
export const GetTeamName = `${h}/team/getNameById`
export const RoomList = `${h}/room/roomList`
export const GetRoomName = `${h}/room/getNameById`
export const CheckNumberForNew = `${h}/student/checkNumberForNew`
export const CheckNumberForEdit = `${h}/student/checkNumberForEdit`
export const CheckCodeForNew = `${h}/student/checkCodeForNew`
export const CheckCodeForEdit = `${h}/student/checkCodeForEdit`
export const Save = `${h}/student/save`
export const Edit = `${h}/student/edit`
export const QueryByName = `${h}/student/queryByName`
export const TotalByName = `${h}/student/totalByName`
export const GetById = `${h}/student/getById`
export const InactiveById = `${h}/student/inactiveById`
export const ActiveById = `${h}/student/activeById`
