const h = ''
// const h = '/ds'
export const CheckNameForNew = `${h}/team/checkNameForNew`
export const CheckNameForEdit = `${h}/team/checkNameForEdit`
export const Save = `${h}/team/save`
export const Edit = `${h}/team/edit`
export const TeacherList = `${h}/team/teacherList`
export const GetTeamTeacher = `${h}/team/getTeamTeacher`
export const QueryByName = `${h}/team/queryByName`
export const TotalByName = `${h}/team/totalByName`
export const GetById = `${h}/team/getById`
export const DeleteById = `${h}/team/deleteById`
